org: luisreis
app: aws-node-http-api
service: aws-node-http-api-project
frameworkVersion: "3"

resources:
  extensions: 
    S3BucketAlunoscsvprod2:
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - POST
                - PUT 
                - GET
                - HEAD
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::alunos-csv-prod2/*

functions:
  cadastrarAlunos:
    handler: create_register_batch/aws/index.cadastrarAlunos
    events:
      - s3:
          bucket: alunos-csv-prod2
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

  simulandoUploadCsv:
    handler: create_register_batch/local/index.simulandoUploadCsv
    events:
      - httpApi:
          path: /alunos/batch
          method: post
    enabled: false

  cadastrarAlunosLocal:
    handler: create_register_batch/local/index.cadastrarAlunosLocal
    events:
      - s3:
          bucket: alunos-csv-local
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
    enabled: false


plugins:
  - serverless-offline
  - serverless-s3-local
  - serverless-disable-functions
